
services:  

  db:
    container_name: ${DB_NAME}
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_DEFAULT_PORT}"
    volumes:
      - hospital-app:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.0-apache
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_ARBITRARY: 1

volumes:
  hospital-app:
    external: false